### ISSUE TITLE
broken after update to v1.2.0

### ISSUE THREAD

**Issue by hackape** [tptee/FlowIDE#13]
keep getting message in console:
```
Invalid context
None
```
using sublime text 3 on macOS, build 3126

**Comment by hackape** [comment]
```
Traceback (most recent call last):
  File "/Users/vince/Library/Application Support/Sublime Text 3/Packages/FlowIDE/flowide/listeners/coverage.py", line 14, in <lambda>
  File "/Users/vince/Library/Application Support/Sublime Text 3/Packages/FlowIDE/flowide/util.py", line 11, in wrapper
  File "/Users/vince/Library/Application Support/Sublime Text 3/Packages/FlowIDE/flowide/util.py", line 20, in debounced
AttributeError: 'NoneType' object has no attribute 'project_data'
```
Related code:
```
# Adapted from https://gist.github.com/walkermatt/2871026
def debounce(func):
    def debounced(self, *args, **kwargs):
        flow_settings = find_flow_settings(
            self.view.window().project_data()   
        )
...
``

**Comment by hackape** [comment]
ah i get it, you no longer allow usage without /* @flow */ hint. Better print out that particular reason, it's in the exception anyway, isn't it?
